### ISSUE TITLE
Making the Brush Stroke Continuous

### ISSUE THREAD

**Issue by sai-deekshith16** [convict-git/KoraKaagaz#121]
The current brush tool on dragging too fast is leaving the gaps and not able to provide a smooth stroke. Correct it and change the shape to draw from rectangle to Square. Also change the canvas it is drawing from canvasB to canvasF.

**Comment by sai-deekshith16** [comment]
Made the changes in the PR #117

**Comment by convict-git** [comment]
Adding for reference.
![Screenshot_20201123-125425_Meet](https://user-images.githubusercontent.com/34399448/100527385-0d511480-31f8-11eb-8b73-545cfe3353c0.jpg)

**Comment by RathoreDevansh08** [comment]
resolved by Anish.
