### ISSUE TITLE
Cant initiate as eclipse project from master branch

### ISSUE THREAD

**Issue by nmnambiar** [convict-git/KoraKaagaz#124]

**Comment by nmnambiar** [comment]
Steps to replicate:

`git checkout master`
try to open eclipse IDE
IDE doesnt seem to recognise KoraKaagaz as a valid Eclipse project

**Comment by nmnambiar** [comment]
the Error states that no .project file could be found
branches seemed to have this file and can be loaded correctly

possible reason this might be occuring:
.project is included in the .gitignore file at master

**Comment by nmnambiar** [comment]
another method to replicate:
go to KoraKaagaz local repo and do `git checkout master`

switch to a different directory and create a new clone of the repo (using `git clone git@github.com:convict-git/KoraKaagaz.git`)
open the repo and try opening the Eclipse IDE at this repo

Eclipse loads fine but doesn't identify the directory as a valid Eclipse project
When I try to open a project, it fails and says: Could not be loaded as a Project, since no .project file was found

Note: my eclipse-workspace is kept a different place (in case that matters)

**Comment by convict-git** [comment]
@nmnambiar I got the issue too now. Looking into it.

**Comment by convict-git** [comment]
> possible reason this might be occuring:
.project is included in the .gitignore file at master

Yes, that is exactly the reason. Without the `.project` file, the project cannot be imported in Eclipse. 
One way to resolve this is, whoever clones the source first creates a project manually on Eclipse. But this is not desirable. 

Hence, I'm going with removing it from `.gitignore`.

**Comment by nmnambiar** [comment]
Saw the commit 3bdb85cbeeed067cca73c7684d02aad5b90a2cf5
Checked in my local repo and eclipse now detects a valid project from master branch

The issue is resolved. It can be closed now
Cheers!

**Comment by nmnambiar** [comment]
Oh wait

**Comment by nmnambiar** [comment]
while the logger module seems to be working fine right now (@Rahul-R5 could you confirm at your end too?), the problem seems to be now come from processing module

I was running a local test case from [Rahul-R5/logger_test](Rahul-R5/KoraKaagaz/tree/logger_test) and observed the following error (among other 35 errors mostly similar ones)

| Description | Resource | Path | Location | Type |
|-----------------|--------------|--------|-------------|--------|
| The type javax.swing.WindowConstants is not accessible |	Visualize.java | /KoraKaagaz/src/processing/visualize | line 11 | 	Java Problem |

/KoraKaagaz/src/processing/visualize : line 11 has
```java
import javax.swing.WindowConstants;
```

did we perhaps miss some project dependencies of other modules?

**Comment by convict-git** [comment]
Yes, @nmnambiar, it seems few people have swing and awt installed with them and few don't.
@sakshi1603 @tymefighter As mentioned earlier, even I'm facing this issue. 

Thanks for pointing out. I thought the issue was only with me.

**Comment by nmnambiar** [comment]
Okay
I think we can create a separate issue for this

**Comment by convict-git** [comment]
Yes, closing this now (.project was added). Can you refer [to this](https://github.com/convict-git/KoraKaagaz/issues/124#issuecomment-735374371) in the new issue? @nmnambiar
