### ISSUE TITLE
Resource leak through sockets

### ISSUE THREAD

**Issue by convict-git** [convict-git/KoraKaagaz#131]
https://github.com/convict-git/KoraKaagaz/blob/3bdb85cbeeed067cca73c7684d02aad5b90a2cf5/src/networking/CommunicatorFactory.java#L150

https://github.com/convict-git/KoraKaagaz/blob/3bdb85cbeeed067cca73c7684d02aad5b90a2cf5/src/networking/server/ServerManager.java#L38

@sravand123 @Prudhvis-gitrepo How are we going to release the sockets?

**Comment by convict-git** [comment]
@sravand123 Any updates?

**Comment by muhammedyaseen-git** [comment]
@sravand123 Please open PR

**Comment by sravand123** [comment]
sure
