### ISSUE TITLE
Errors observed from processing module during testing

### ISSUE THREAD

**Issue by nmnambiar** [convict-git/KoraKaagaz#134]
When I updated to the latest master and was testing out the new logger, there seems to be an error during build. The problem seems to be now come from processing module

### What I did
I was running a test case locally by rebasing the latest master with test files at [Rahul-R5/logger_test](Rahul-R5/KoraKaagaz/tree/logger_test). The logger test cases ran successfully. However, I observed the following error from the processor module (among other 35 errors mostly similar ones)

### Received Output

| Description | Resource | Path | Location | Type |
|-----------------|--------------|--------|-------------|--------|
| The type javax.swing.WindowConstants is not accessible |	Visualize.java | /KoraKaagaz/src/processing/visualize | line 11 | 	Java Problem |

### Additional Info
/KoraKaagaz/src/processing/visualize : line 11 has
```java
import javax.swing.WindowConstants;
```

did we perhaps miss some project dependencies of other modules?

**Comment by sakshi1603** [comment]
Can you try including `requires java.desktop` in module.info. As @tymefighter and I didn't get this error, I'm not sure whether this will work or not. Can you try this and confirm?

**Comment by himanshu2047** [comment]
When we add module-info.java file in the project, then it will load libraries written in them only. So earlier when module-info.java was not there, it was working fine and when I pulled the latest one, it showed me errors, we need to add `requires java.desktop` in it to include the awt and swing pacakges.

**Comment by curche** [comment]
Thanks for the info @sakshi1603 @himanshu2047 
I think that should resolve it. It is better to be explicit in module-info.java files
Then I guess the processing module can PR it to upstream.
I will check whether the PR branch works in my local Eclipse

**Comment by nmnambiar** [comment]
Thanks for the info @sakshi1603 @himanshu2047
I think that should resolve it. It is better to be explicit in module-info.java files
Then I guess the processing module can PR it to upstream.
I will check whether the PR branch works in my local Eclipse
