### ISSUE TITLE
BoardID in UI

### ISSUE THREAD

**Issue by himanshu2047** [convict-git/KoraKaagaz#137]
When you are passing BoardID in `initialiseUser()` function of processing, it should be null if the user didn't entered as we discussed instead we are getting empty string. Please look into it. @sai-deekshith16

**Comment by sai-deekshith16** [comment]
Thanks for the notice. @ShivaDhanushK will look into it today.

**Comment by muhammedyaseen-git** [comment]
@ShivaDhanushK can you give an update?

**Comment by convict-git** [comment]
@sai-deekshith16 This should be easy to handle, I guess. Please let us know any updates on this.

**Comment by sai-deekshith16** [comment]
> @sai-deekshith16 This should be easy to handle, I guess. Please let us know any updates on this.

This has been resolved and has the corrected code in the Complete UI module PR.
