### ISSUE TITLE
Default configurations in infrastructure_logger.xml

### ISSUE THREAD

**Issue by sakshi1603** [convict-git/KoraKaagaz#138]
Default for testing_logger.xml in `resources/infrastructure_logger.xml` should be set as false.

**Comment by muhammedyaseen-git** [comment]
@Rahul-R5 please see this

**Comment by nmnambiar** [comment]
my bad, few stray stuff that remained while we were testing out logger settings
I can fix it pretty quick

**Comment by Rahul-R5** [comment]
@muhammedyaseen-git PR opened
