### ISSUE TITLE
Logger not Working in Jar

### ISSUE THREAD

**Issue by himanshu2047** [convict-git/KoraKaagaz#146]
Logger is not working in executable jar file as the configuration file path is not set properly, it should be outside jar somewhere.

This issue is resolved, just creating to send the pr by @nmnambiar

**Comment by nmnambiar** [comment]
the jar doesnt seem to package the `resources/infrastructure_logger.xml` in all cases (it worked fine for me but not for few others)

I'll add an external location from where an xml can be kept like `$HOME/.config/KoraKaagaz/infrastructure_logger.xml`
it would be better for normal user testing too, I guess

**Comment by sakshi1603** [comment]
Also update the location of log files in your Spec. @nmnambiar

**Comment by nmnambiar** [comment]
@Rahul-R5 @convict-git PR ready at L2
