### ISSUE TITLE
full Communicator Factory class with giving ip and port

### ISSUE THREAD

**Issue by Prudhvis-gitrepo** [convict-git/KoraKaagaz#79]
Tried to implement the new feature with in the short period of time.

**Comment by muhammedyaseen-git** [comment]
`sock.connect(InetAddress.getByName("10.0.0.0"),1024);`
What does this line do? @Prudhvis-gitrepo @sravand123

**Comment by Prudhvis-gitrepo** [comment]
@muhammedyaseen-git This line helps to get the local or private IP of the client. Feel free to remove the line and try to get private IP you might get 0.0.0.0.
