### ISSUE TITLE
Adding controllers,main.java and updating canvas fxml file

### ISSUE THREAD

**Issue by ShivaDhanushK** [convict-git/KoraKaagaz#98]
Whiteboard controller handles transition from Startsession fxml to canvas fxml
adding canvas controller which handles operations being done inside canvas fxml page.
Adding main.java file
updating canvas fxml to include menu items and shape items

**Comment by convict-git** [comment]
@sai-deekshith16 This open issue isn't referenced in any open PR now. Please clarify.

**Comment by convict-git** [comment]
If it should get closed in #117. Then please refer it there.

**Comment by sai-deekshith16** [comment]
Thanks for notifying I added it in the #117
